# Generated by Django 2.2.6 on 2019-10-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20191011_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingform',
            name='book_from',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='book_until',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
