# Generated by Django 2.2.6 on 2019-10-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_bookingdata_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdata',
            name='room',
            field=models.CharField(choices=[('Gynasium', 'Gym'), ('Dance Room', 'Dance Studio'), ('Weight Room', 'Workout Room')], default='Gym', max_length=30),
        ),
    ]
