# Generated by Django 2.2.6 on 2019-10-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20191016_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdata',
            name='date',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
