# Generated by Django 2.2.6 on 2019-10-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_bookingdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdata',
            name='book_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingdata',
            name='book_until',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingdata',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingdata',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
    ]
