# Generated by Django 2.2.6 on 2019-10-24 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20191018_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingdata',
            old_name='book_from',
            new_name='book_from_ex',
        ),
        migrations.RenameField(
            model_name='bookingdata',
            old_name='book_until',
            new_name='book_until_ex',
        ),
        migrations.RenameField(
            model_name='bookingdata',
            old_name='comments',
            new_name='comments_ex',
        ),
        migrations.RenameField(
            model_name='bookingdata',
            old_name='date',
            new_name='date_ex',
        ),
        migrations.RenameField(
            model_name='bookingdata',
            old_name='email',
            new_name='email_ex',
        ),
        migrations.RenameField(
            model_name='bookingdata',
            old_name='first_name',
            new_name='first_name_ex',
        ),
        migrations.RenameField(
            model_name='bookingdata',
            old_name='last_name',
            new_name='last_name_ex',
        ),
        migrations.RenameField(
            model_name='bookingdata',
            old_name='room',
            new_name='room_ex',
        ),
    ]
