# Generated by Django 2.2.6 on 2019-10-24 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20191024_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingdata',
            old_name='book_from_ex',
            new_name='book_from',
        ),
        migrations.RenameField(
            model_name='bookingdata',
            old_name='book_until_ex',
            new_name='book_until',
        ),
        migrations.RenameField(
            model_name='bookingdata',
            old_name='comments_ex',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='bookingdata',
            old_name='date_ex',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='bookingdata',
            old_name='email_ex',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='bookingdata',
            old_name='first_name_ex',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='bookingdata',
            old_name='last_name_ex',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='bookingdata',
            old_name='room_ex',
            new_name='room',
        ),
    ]
