# Generated by Django 2.2.6 on 2019-12-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorekeep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecreate',
            name='awayScore',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='scorecreate',
            name='homeScore',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='scorecreate',
            name='slug',
            field=models.SlugField(default=1, null=True, unique=True),
        ),
    ]
