# Generated by Django 2.2.6 on 2019-12-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorekeep', '0002_auto_20191218_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecreate',
            name='sport',
            field=models.CharField(choices=[('BB', 'Basketball'), ('VB', 'Volleyball')], default='VB', max_length=2),
        ),
    ]
