# Generated by Django 2.2.6 on 2019-12-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorekeep', '0003_scorecreate_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecreate',
            name='away',
            field=models.CharField(max_length=120),
        ),
    ]
